export enum  Role {
   ROLE_AGENT_NAVA = 'ROLE_AGENT_NAVA',
   ROLE_DISPECER_ANR = 'ROLE_DISPECER_ANR',
   ROLE_DISPECER_APMC = 'ROLE_DISPECER_APMC',
   ROLE_DISPECER_PILOTAJ = 'ROLE_DISPECER_PILOTAJ',
   ROLE_OPERATOR = 'ROLE_OPERATOR'
}
