spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    liquibase-schema: ge
  jpa:
    properties:
      hibernate.default_schema: ge
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ge
server:
  port: 8081
logging:
  level:
    org.springframework.security: trace