spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    liquibase-schema: ge
  jpa:
    properties:
      hibernate.default_schema: ge